# Generated by Django 6.0.1 on 2026-01-30 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Data Sources',
                'db_table': 'data_sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iso_code', models.CharField(blank=True, max_length=2, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='idx_country_name'), models.Index(fields=['iso_code'], name='idx_country_code')],
            },
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_normalized', models.CharField(help_text='Lowercase, accents removed for search', max_length=255)),
                ('birth_year', models.SmallIntegerField(blank=True, null=True)),
                ('death_year', models.SmallIntegerField(blank=True, null=True)),
                ('is_living', models.BooleanField(default=False)),
                ('country_description', models.TextField(blank=True, help_text="For complex origins like 'American composer of Brazilian origin'", null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('period', models.CharField(blank=True, choices=[('Renaissance', 'Renaissance'), ('Baroque', 'Baroque'), ('Classical', 'Classical'), ('Romantic', 'Romantic'), ('Modern', 'Modern'), ('Contemporary', 'Contemporary')], max_length=50, null=True)),
                ('external_id', models.CharField(blank=True, help_text='Original ID from source', max_length=100, null=True)),
                ('imslp_url', models.URLField(blank=True, max_length=255, null=True)),
                ('wikipedia_url', models.URLField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.country')),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.datasource')),
            ],
            options={
                'db_table': 'composers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Instrumentation Categories',
                'db_table': 'instrumentation_categories',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['name'], name='idx_instrumentation_name')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, help_text="'genre', 'style', 'technique', 'form', etc.", max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='idx_tag_name'), models.Index(fields=['slug'], name='idx_tag_slug'), models.Index(fields=['category'], name='idx_tag_category'), models.Index(fields=['usage_count'], name='idx_tag_usage')],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title_normalized', models.CharField(help_text='Lowercase, accents removed for search', max_length=500)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('opus_number', models.CharField(blank=True, max_length=50, null=True)),
                ('catalog_number', models.CharField(blank=True, max_length=100, null=True)),
                ('composition_year', models.SmallIntegerField(blank=True, null=True)),
                ('composition_year_approx', models.BooleanField(default=False)),
                ('duration_minutes', models.SmallIntegerField(blank=True, null=True)),
                ('instrumentation_detail', models.TextField(blank=True, help_text='Original instrumentation string from source', null=True)),
                ('difficulty_level', models.SmallIntegerField(blank=True, help_text='1-10 scale', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('movements', models.TextField(blank=True, help_text='JSON array or delimited list', null=True)),
                ('key_signature', models.CharField(blank=True, max_length=50, null=True)),
                ('imslp_url', models.URLField(blank=True, max_length=255, null=True)),
                ('youtube_url', models.URLField(blank=True, max_length=255, null=True)),
                ('score_url', models.URLField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='music.composer')),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.datasource')),
                ('instrumentation_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.instrumentationcategory')),
            ],
            options={
                'db_table': 'works',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WorkSearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composer_full_name', models.CharField(max_length=255)),
                ('composer_last_name', models.CharField(max_length=100)),
                ('composer_country', models.CharField(blank=True, max_length=100, null=True)),
                ('composer_birth_year', models.SmallIntegerField(blank=True, null=True)),
                ('composer_death_year', models.SmallIntegerField(blank=True, null=True)),
                ('work_title', models.CharField(max_length=500)),
                ('work_instrumentation', models.CharField(blank=True, max_length=200, null=True)),
                ('work_year', models.SmallIntegerField(blank=True, null=True)),
                ('search_text', models.TextField(help_text='Combines all searchable fields')),
                ('popularity_score', models.FloatField(default=0.0)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_index', to='music.work')),
            ],
            options={
                'db_table': 'work_search_index',
            },
        ),
        migrations.CreateModel(
            name='WorkTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_tags', to='music.tag')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_tags', to='music.work')),
            ],
            options={
                'db_table': 'work_tags',
            },
        ),
        migrations.CreateModel(
            name='ComposerAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(max_length=255)),
                ('alias_type', models.CharField(choices=[('birth_name', 'Birth Name'), ('stage_name', 'Stage Name'), ('alternate_spelling', 'Alternate Spelling'), ('pseudonym', 'Pseudonym'), ('translation', 'Translation')], default='alternate_spelling', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='music.composer')),
            ],
            options={
                'verbose_name_plural': 'Composer Aliases',
                'db_table': 'composer_aliases',
                'indexes': [models.Index(fields=['composer'], name='idx_alias_composer'), models.Index(fields=['alias_name'], name='idx_alias_name')],
            },
        ),
        migrations.AddIndex(
            model_name='composer',
            index=models.Index(fields=['last_name'], name='idx_composer_last_name'),
        ),
        migrations.AddIndex(
            model_name='composer',
            index=models.Index(fields=['full_name'], name='idx_composer_full_name'),
        ),
        migrations.AddIndex(
            model_name='composer',
            index=models.Index(fields=['name_normalized'], name='idx_composer_normalized'),
        ),
        migrations.AddIndex(
            model_name='composer',
            index=models.Index(fields=['country'], name='idx_composer_country'),
        ),
        migrations.AddIndex(
            model_name='composer',
            index=models.Index(fields=['birth_year'], name='idx_composer_birth_year'),
        ),
        migrations.AddIndex(
            model_name='composer',
            index=models.Index(fields=['death_year'], name='idx_composer_death_year'),
        ),
        migrations.AddIndex(
            model_name='composer',
            index=models.Index(fields=['period'], name='idx_composer_period'),
        ),
        migrations.AddIndex(
            model_name='composer',
            index=models.Index(fields=['is_living'], name='idx_composer_living'),
        ),
        migrations.AddIndex(
            model_name='composer',
            index=models.Index(fields=['is_verified'], name='idx_composer_verified'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['composer'], name='idx_work_composer'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['title'], name='idx_work_title'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['title_normalized'], name='idx_work_normalized'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['instrumentation_category'], name='idx_work_instrumentation'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['composition_year'], name='idx_work_year'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['difficulty_level'], name='idx_work_difficulty'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['is_public'], name='idx_work_public'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['is_verified'], name='idx_work_is_verified'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['view_count'], name='idx_work_views'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['composer', 'is_public'], name='idx_work_comp_public'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['composer', 'is_verified'], name='idx_work_comp_verified'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['instrumentation_category', 'is_public'], name='idx_work_inst_public'),
        ),
        migrations.AddIndex(
            model_name='worksearchindex',
            index=models.Index(fields=['composer_last_name'], name='idx_search_composer_last'),
        ),
        migrations.AddIndex(
            model_name='worksearchindex',
            index=models.Index(fields=['composer_full_name'], name='idx_search_composer_full'),
        ),
        migrations.AddIndex(
            model_name='worksearchindex',
            index=models.Index(fields=['work_title'], name='idx_search_work_title'),
        ),
        migrations.AddIndex(
            model_name='worksearchindex',
            index=models.Index(fields=['work_instrumentation'], name='idx_search_instrumentation'),
        ),
        migrations.AddIndex(
            model_name='worksearchindex',
            index=models.Index(fields=['work_year'], name='idx_search_year'),
        ),
        migrations.AddIndex(
            model_name='worksearchindex',
            index=models.Index(fields=['popularity_score'], name='idx_search_popularity'),
        ),
        migrations.AddIndex(
            model_name='worktag',
            index=models.Index(fields=['work'], name='idx_work_tags_work'),
        ),
        migrations.AddIndex(
            model_name='worktag',
            index=models.Index(fields=['tag'], name='idx_work_tags_tag'),
        ),
        migrations.AlterUniqueTogether(
            name='worktag',
            unique_together={('work', 'tag')},
        ),
    ]
