# Generated by Django 6.0.1 on 2026-01-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='is_living',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
