# Generated by Django 6.0.1 on 2026-07-13 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_add_trigram_search_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Display text, e.g. 'BCGS Commission'", max_length=200)),
                ('url', models.URLField(max_length=1000)),
                ('link_type', models.CharField(choices=[('imslp', 'IMSLP'), ('sheerpluck', 'SheerPluck'), ('youtube', 'YouTube'), ('score', 'Score'), ('publisher', 'Publisher'), ('recording', 'Recording'), ('commission', 'Commission / Program'), ('other', 'Other')], default='other', help_text='Drives the icon / CTA styling; label is the shown text', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='music.work')),
            ],
            options={
                'db_table': 'work_links',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['work'], name='idx_work_links_work'), models.Index(fields=['link_type'], name='idx_work_links_type')],
                'unique_together': {('work', 'url')},
            },
        ),
    ]
