# Generated by Django 6.0.1 on 2026-07-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    """Schema only — no RunPython, by construction.

    `web`'s entrypoint runs `migrate` on every start under `set -e`, so a failed data
    migration crash-loops the container and takes /api down. Tagging the existing
    arrangements and importing the rest is `import_imslp_arrangements`, a management
    command run by hand. Until it runs, the "Include arrangements" checkbox simply has
    nothing to hide — degradation, not an outage.
    """

    dependencies = [
        ('music', '0015_work_instrumentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='arrangement_basis',
            field=models.CharField(blank=True, choices=[('derived', 'Derived'), ('suggested', 'Suggested'), ('manual', 'Manual')], default='', help_text="Where is_arrangement came from; blank means undecided. The importer rewrites 'derived' and blank only, so a human's call survives every backfill.", max_length=10),
        ),
        migrations.AddField(
            model_name='work',
            name='is_arrangement',
            field=models.BooleanField(db_index=True, default=False, help_text='Arranged/transcribed for guitar rather than originally written for it'),
        ),
    ]
